version: 2.1

workflows:
  version: 2
  api_verify:
    jobs:
      - verify

executors:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/SkyAPM/go2sky

jobs:
  verify:
    executor: build
    steps:
      - checkout
      - run: make test
      - run: make lint
